services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_db
    ports:
      - "3306:3306"
    volumes:
      - hospital_mysql_db_data:/var/lib/mysql
      - ./db/1_schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./db/2_users.sql:/docker-entrypoint-initdb.d/2_users.sql

  mongodb:
    hostname: mongodb
    image: mongodb/mongodb-atlas-local
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27019:27017"
    volumes:
      - data:/data/db
      - config:/data/configdb

volumes:
  hospital_mysql_db_data:
  data:
  config: